### ISSUE TITLE
Knapper har ulik farge i dark-modus

### ISSUE THREAD

**Issue by RanyTB** [OleHalvorE/FinalProject#3]
![2018-11-27 14_30_22-visionx](https://user-images.githubusercontent.com/43849600/49084964-362d2080-f251-11e8-88ad-0a7ee640bc5d.png)
![2018-11-27 14_30_41-visionx](https://user-images.githubusercontent.com/43849600/49084966-36c5b700-f251-11e8-8492-3bfe36869bec.png)

**Comment by RanyTB** [comment]
Fiks hvite knapper på toppen i dark mode

**Comment by eirikboy** [comment]
working 9-5

**Comment by eirikboy** [comment]
Siri: working 1015-?

**Comment by eirikboy** [comment]
if( item.className.split(" ")[0] == "playerbtn" || item.id == "contrast" || item.id == "fontSize")
